export const baseUrl = "https://res.cloudinary.com/dxzycbpry/image/upload/v1766323080/lendsqr-assets";
const Assets = {
    //png
    USERS_IMAGE: `${baseUrl}/user-image_avy1xt.png`,
    PABLO_SIGN_IN_ICON: `${baseUrl}/pablo-sign-in_1_zkv7ra.png`,

    //svg
    GUARANTORS_ICON: `${baseUrl}/guarantors_hv3jce.svg`,
    WHITELIST_ICON: `${baseUrl}/whitelist_qvq1kh.svg`,
    VIEW_DETAILS_ICON: `${baseUrl}/view-details_zhudcl.svg`,
    USERS_WITH_SAVINGS_ICON: `${baseUrl}/users-with-savings_mddjsh.svg`,
    USERS_ICON: `${baseUrl}/users_twz5op.svg`,
    USERS_2_ICON: `${baseUrl}/users-icon_gsh1bb.svg`,
    USERS_WITH_LOANS_ICON: `${baseUrl}/users-with-loans_ulv6sc.svg`,
    SWITCH_ORGANIZATION_ICON: `${baseUrl}/switch-organization_okwdjk.svg`,
    TRANSACTIONS_ICON: `${baseUrl}/transactions_bbpkzo.svg`,
    SEARCH_ICON: `${baseUrl}/search_ut61he.svg`,
    SERVICES_ICON: `${baseUrl}/services_blswpd.svg`,
    SETTLEMENTS_ICON: `${baseUrl}/settlements_q4vrzs.svg`,
    SERVICE_ACCOUNT_ICON: `${baseUrl}/service-account_nobyfk.svg`,
    SAVINGS_ICON: `${baseUrl}/savings_kyjnfe.svg`,
    SAVING_PRODUCTS_ICON: `${baseUrl}/saving-products_au5dmd.svg`,
    PREFERENCES_ICON: `${baseUrl}/preferences_nnhzeq.svg`,
    ORGANIZATION_ICON: `${baseUrl}/organization_sgqyl8.svg`,
    PREV_BTN_ICON: `${baseUrl}/prev-btn-icon_cireqo.svg`,
    NEXT_BTN_ICON: `${baseUrl}/next-btn-icon_jt7and.svg`,
    NOTIFICATION_BELL_ICON: `${baseUrl}/notification-bell_z26qko.svg`,
    LENDSQR_LOGO_ICON: `${baseUrl}/lendsqr-logo_bx3kar.svg`,
    LENDSQR_LOGO_GROUP_ICON: `${baseUrl}/lendsqr-logo-group_fqaxkt.svg`,
    LOAN_PRODUCTS_ICON: `${baseUrl}/loan-products_l3w1b4.svg`,
    LOAN_REQUESTS_ICON: `${baseUrl}/loan-requests_iteiwe.svg`,
    LOANS_ICON: `${baseUrl}/loans_olq6le.svg`,
    KARMA_ICON: `${baseUrl}/karma_nqlqtx.svg`,
    FEES_AND_PRICING_ICON: `${baseUrl}/fees-and-pricing_jswyzq.svg`,
    FEES_AND_CHARGES_ICON: `${baseUrl}/fees-and-charges_cyv5yt.svg`,
    DECISION_MODELS_ICON: `${baseUrl}/decision-models_qlxrxg.svg`,
    DROPDOWN_ICON: `${baseUrl}/dropdown_rjooze.svg`,
    AVATAR_1_ICON: `${baseUrl}/avatar-1_kqu01c.svg`,
    ACTIVATE_USER_ICON: `${baseUrl}/activate-user_le8seu.svg`,
    AUDIT_LOGS_ICON: `${baseUrl}/audit-logs_dtxcwx.svg`,
    BLACKLIST_USER_ICON: `${baseUrl}/blacklist-user_bgnmzu.svg`,
    FILTER_BUTTON_ICON: `${baseUrl}/filter-button_wz6omu.svg`,
    DASHBOARD_ICON: `${baseUrl}/dashboard_gmyfo6.svg`,
    ACTIVE_USERS_ICON: `${baseUrl}/active-users_xmpb0w.svg`,
    BACK_ARROW_ICON: `${baseUrl}/back-arrow_ysmyhh.svg`,
    MORE_ICON: `${baseUrl}/more-icon_r2uafa.svg`,
    STAR_EMPTY_ICON: `${baseUrl}/star-empty-icon_ucidww.svg`,
    STAR_FILLED_ICON: `${baseUrl}/star-filled-icon_guotme.svg`,
    CHEVRON_DOWN_ICON: `${baseUrl}/chevron-down-icon_fdhuvr.svg`,
    CHECK_ICON: `${baseUrl}/check-icon_xzgcep.svg`,
    LOGOUT_ICON: `${baseUrl}/logout-icon_opmfak.svg`,
    HAMBURGER_ICON: `${baseUrl}/hamburger-icon_v48xgm.svg`,
    CLOSE_ICON: `${baseUrl}/close-icon_i1mbgm.svg`,
    SORT_UP_ICON: `${baseUrl}/sort-up_mdwffe.svg`,
    SORT_DOWN_ICON: `${baseUrl}/sort-down_dohiit.svg`,
};

export default Assets;
